# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

#' get_info_data
#' 
#' @param df un dataframe
#'
#' @return une liste contenant le nombre de lignes et de colonnes du dataframe
#' 
#' @export
#' @examples
#' get_info_data(iris)
#' get_info_data(mtcars)
#'
get_info_data <- function(df) {
  if (isFALSE(inherits(df, "data.frame")))  {
    stop("mydata is not a data frame")
  }
  return(list(nrow(df), length(df), names(df)))
}
