# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

#' get_mean_data
#' 
#' créer une fonction qui permettra d’obtenir une table avec la moyenne de toutes les variables numériques de votre jeu de donnée en paramètre
#'
#' 
#' @param df un dataframe
#'
#' @return une table
#' 
#' @export
#' @examples
#' get_mean_data(iris)
#' get_mean_data(mtcars)
get_mean_data <- function(df) {
  df |> dplyr::summarise(dplyr::across(is.numeric, mean))
}
